from utils import ...

class LoanClassifier():

    def __init__(self, data):
        processed_data = ...
        std_process_data = ...
        woe_process_data = ...

        ...

    def evaluate(models: str = "all"):
        if models == "all":
            ...
        elif ...:
            ...

    
    def roc_plot(self):
        ...
        
    def predictions(self):
        ...